// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using New_Hardware_Management_System;

#nullable disable

namespace New_Hardware_Management_System.Migrations
{
    [DbContext(typeof(HardwareDbContext))]
    partial class HardwareDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("New_Hardware_Management_System.Models.Steel_Rods", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Brand")
                        .HasColumnType("longtext");

                    b.Property<int?>("Length")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SteelRods");
                });

            modelBuilder.Entity("New_Hardware_Management_System.Models.item", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<double>("BuyingPrice")
                        .HasColumnType("double");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("varchar(21)");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<double>("SellingPrice")
                        .HasColumnType("double");

                    b.HasKey("ItemId");

                    b.ToTable("Items");

                    b.HasDiscriminator<string>("Discriminator").HasValue("item");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("New_Hardware_Management_System.Models.Cement", b =>
                {
                    b.HasBaseType("New_Hardware_Management_System.Models.item");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Quality")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.ToTable("Items", t =>
                        {
                            t.Property("Brand")
                                .HasColumnName("Cement_Brand");

                            t.Property("Quality")
                                .HasColumnName("Cement_Quality");
                        });

                    b.HasDiscriminator().HasValue("Cement");
                });

            modelBuilder.Entity("New_Hardware_Management_System.Models.Electrical_Appliances", b =>
                {
                    b.HasBaseType("New_Hardware_Management_System.Models.item");

                    b.HasDiscriminator().HasValue("Electrical_Appliances");
                });

            modelBuilder.Entity("New_Hardware_Management_System.Models.Home_Appliances", b =>
                {
                    b.HasBaseType("New_Hardware_Management_System.Models.item");

                    b.HasDiscriminator().HasValue("Home_Appliances");
                });

            modelBuilder.Entity("New_Hardware_Management_System.Models.Nails", b =>
                {
                    b.HasBaseType("New_Hardware_Management_System.Models.item");

                    b.Property<int?>("Diameter")
                        .HasColumnType("int");

                    b.Property<int?>("Length")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Nails");
                });

            modelBuilder.Entity("New_Hardware_Management_System.Models.Paint", b =>
                {
                    b.HasBaseType("New_Hardware_Management_System.Models.item");

                    b.Property<string>("Brand")
                        .HasColumnType("longtext");

                    b.Property<int?>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Colour")
                        .HasColumnType("longtext");

                    b.Property<string>("ColourCode")
                        .HasColumnType("longtext");

                    b.Property<string>("Quality")
                        .HasColumnType("longtext");

                    b.HasDiscriminator().HasValue("Paint");
                });

            modelBuilder.Entity("New_Hardware_Management_System.Models.Bulb", b =>
                {
                    b.HasBaseType("New_Hardware_Management_System.Models.Electrical_Appliances");

                    b.Property<string>("Brand")
                        .HasColumnType("longtext");

                    b.Property<string>("Type")
                        .HasColumnType("longtext");

                    b.Property<double?>("Voltage")
                        .HasColumnType("double");

                    b.ToTable("Items", t =>
                        {
                            t.Property("Brand")
                                .HasColumnName("Bulb_Brand");
                        });

                    b.HasDiscriminator().HasValue("Bulb");
                });
#pragma warning restore 612, 618
        }
    }
}
